# Generated by Django 4.2.18 on 2025-02-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0036_job_hotkey_alter_job_user_job_idx_job_hotkey_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="on_trusted_miner",
            field=models.BooleanField(default=False),
        ),
    ]
