# Generated by Django 4.2.18 on 2025-02-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0037_alter_job_volumes"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="on_trusted_miner",
            field=models.BooleanField(default=False),
        ),
    ]
