name: Run linter and tests

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

env:
  PYTHON_DEFAULT_VERSION: "3.11"

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python ${{ env.PYTHON_DEFAULT_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_DEFAULT_VERSION }}
          cache: "pip"
      - name: Install dependencies
        run: python -m pip install --upgrade nox pdm==2.19.3
      - name: Run linters
        run: nox -vs lint
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - id: app_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PEM }}
          owner: ${{ github.repository_owner }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python ${{ env.PYTHON_DEFAULT_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_DEFAULT_VERSION }}
          cache: "pip"
      - name: Install dependencies
        run: python -m pip install --upgrade nox pdm==2.19.3
      - name: Prepare environment
        run: ./setup-dev.sh
      - name: Install additional packages
        run: |
          set -e
          export GITHUB_TOKEN="${{ steps.app_token.outputs.token }}"
          export ADDITIONAL_PACKAGES="${{ vars.ADDITIONAL_PACKAGES }}"
          export HTTP_ASGI_APPLICATION_PATH="${{ vars.HTTP_ASGI_APPLICATION_PATH }}"
          [ -n "$ADDITIONAL_PACKAGES" ] && echo "$ADDITIONAL_PACKAGES" | sed "s/\$GITHUB_TOKEN/$GITHUB_TOKEN/g" > additional-packages.txt
          echo "Additional packages: $(cat additional-packages.txt)"
          pip install -r additional-packages.txt
      - name: Run dockerized services
        run: docker compose up -d --wait
      - name: Run migrations
        run: cd app/src && pdm run python manage.py wait_for_database --timeout 120 && pdm run python manage.py migrate
      - name: Run unit tests
        run: nox -vs test
      - name: Stop dockerized services
        if: success() || failure()
        run: docker compose down -v
